config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :movies, param: :slug
    resources :categories
  end
  namespace :api do
    post 'save-rating', to: 'ratings#save'
  end
  resources :movies, only: [:index, :show], param: :slug
  resources :categories, only: [:show], param: :slug
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/category.rb
class Category < ApplicationRecord
    before_create :set_slug
    has_many :movies
    def to_param
        slug
    end
    private
    def set_slug
        slug = self.title.parameterize
        count = Category.where("slug LIKE '#{slug}'").count
        self.slug = count.positive? ? "#{slug}-#{count + 1}" : slug
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by slug: params[:id]
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show ]

  def show
    @movies = @category.movies.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    @category_options = Category.all
    render template: "movies/index"
  end

  private
    def set_category
      @category = Category.find_by slug: params[:slug]
    end

    def movie_params
      params.require(:category).permit(:title, :slug)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">

    <p>
        <strong>Title:</strong>
        <%= category.title %>
    </p>

</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", admin_category_path(category) %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", admin_category_path(@category), method: :delete %>
</div>