config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :movies, param: :slug
    resources :categories
  end
  namespace :api do
    post 'save-rating', to: 'ratings#save'
  end
  resources :movies, only: [:index, :show], param: :slug
  resources :categories, only: [:show], param: :slug
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    
  <div class="container">    
    <div class="row content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">IMDb</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
            
              <%= link_to "Movies", root_path, class: "nav-link" %>

            </li>
            
          </ul>
          
            <ul class="navbar-nav float-right">

              <% if user_signed_in? %>
                <li class="nav-item">
                  <span class="nav-link"><strong>Signed in as <%= current_user.email %></strong></span>
                </li>
                <% if current_user.admin? %>
                  <li class="nav-item">
                    <%= link_to "Admin Dashboard", admin_movies_path, class: "nav-link" %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= button_to "Log Out",destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
          </ul>
          
        </div>
      </nav>

      <% if user_signed_in? and current_user.admin? and request.path.starts_with?('/admin') %>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Categories", admin_categories_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Movies", admin_movies_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Users", admin_users_path, class: "nav-link" %>
              </li>
            </ul>
        </nav>

      <% end %>

    <%= yield %>

    </div>
  </div>

  </body>
</html>